services:
  backend:
    image: ${DOCKER_REGISTRY_SERVER_URL}/backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}

  frontend:
    image: ${DOCKER_REGISTRY_SERVER_URL}/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend